apiVersion: v1
kind: Secret
metadata:
  name: collab-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | quote }}
  mongo-uri: "mongodb://collab-mongodb:27017/collabdb"
